version: "3.8"
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    command: '/bin/sh -c ''while :; do sleep 336h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
      - default

  db:
    image: postgres:12
    volumes:
      - ./docker/postgres/pg_data/:/var/lib/postgresql/data/pgdata
    env_file:
      - .prod.full.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - app-network
      - default


  backend:
    image: backend:latest-prod-full
    depends_on:
      - db
      - rabbitmq
      - redis
    env_file:
      - .prod.full.env
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 8000
    volumes:
      - ./app:/app
    networks:
      - app-network
      - default

  celery:
    image: celery:latest-prod-full
    env_file:
      - .prod.full.env
    build:
      context: .
      dockerfile: celery.Dockerfile
    ports:
      - 8000
    depends_on:
      - backend
    volumes:
      - ./app:/app
    networks:
      - app-network
      - default

  flower:
    image: flower:latest-prod-full
    container_name: flower
    build:
      context: .
      dockerfile: flower.Dockerfile
    env_file:
      - .prod.full.env
    volumes:
      - ./app:/app
    ports:
      - 8888
    networks:
      - app-network
      - default

  redis:
    image: redis
    container_name: redis
    env_file:
      - .prod.full.env
    command: [ "redis-server", "/docker/redis/redis.conf" ]
    ports:
      - 6379
    volumes:
      - ./docker/redis/redis-data:/data/bases
      - ./docker/redis/redis.conf:/docker/redis/redis.conf
      - ./docker/redis/log:/docker/redis/log

  rabbitmq:
    image: rabbitmq:3.8.4-management
    container_name: rabbitmq
    env_file:
      - .prod.full.env
    volumes:
      - ./docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672
      - 15672
    networks:
      - app-network
      - default

  pgadmin:
    image: dpage/pgadmin4
    ports:
    - 5050
    depends_on:
      - db
    env_file:
      - .prod.full.env
    networks:
      - app-network
      - default

  certbot:
    container_name: certbot
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 118h & wait $${!}; done;'"
    image: certbot/certbot
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    networks:
      - app-network
      - default


networks:
  app-network:
    external: true
  default:
    external: false