# Change this if needed
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.tls]

# REMOVE this section if you don't want the dashboard/API
[api]
entryPoint = "traefik"
dashboard = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "hhparser.awkr.site"
watch = true
# I prefer to expose my containers explicitly
exposedbydefault = false


[certificatesResolvers.parser.acme]
  email = "terr.kuzyashin@gmail.com"
  storage = "traefik/acme.json"
  [certificatesResolvers.parser.acme.httpChallenge]
    # used during the challenge
    entryPoint = "http"