# Change this if needed
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.tls]

# REMOVE this section if you don't want the dashboard/API
[http.routers.api]
  rule = "Host(`traefik.hhparser.awkr.site`)"
  service = "api@internal"
  middlewares = ["auth"]

[http.middlewares.auth.basicAuth]
  users = [
    "awaker:$$apr1$$fjUPC25L$$eXYA/ozckyqZTVN1WDGVY0",
  ]

[retry]

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "hhparser.awkr.site"
  watch = true
  exposedbydefault = false


[certificatesResolvers.parser.acme]
  email = "terr.kuzyashin@gmail.com"
  storage = "traefik/acme.json"
  [certificatesResolvers.parser.acme.httpChallenge]
    # used during the challenge
    entryPoint = "http"